# Swagger API doc
FROM swaggerapi/swagger-ui

COPY ./docs/swagger /usr/share/nginx/html/swagger

ENV URLS="[{name:\"Auth Microservice\", url:\"/swagger/swagger.yml\"}]"

CMD ["sh", "/usr/share/nginx/run.sh"]